# Generated by Django 5.0.4 on 2026-05-09 07:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_order_amount_paid_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('Utilities', 'Utilities'), ('Salaries', 'Salaries'), ('Supplies', 'Supplies'), ('Rent', 'Rent'), ('Marketing', 'Marketing'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
